### ISSUE TITLE
Where I can select the sync intervall of shopping list?

### ISSUE THREAD

**Issue by Timsche2210** [vlebourl/shopping_list#10]
Hi there,

last point of your readme: "Sync from Bring to HA".
Can you please explain, where I can find / or set up the manually sync?
How can I "activate" or find the service shopping_list.bring_sync?
HA and HACS is very new to me and I am not sure, if I am at the correct folder...
Integration and login were successfull and I see the old items at the bring list

**Comment by Camatobe** [comment]
https://github.com/vlebourl/shopping_list#sync-from-bring-to-ha

You refer to this part of the documentation I guess.
Just follow the Steps stated there:

> add an automation that syncs Bring to HA every few minutes, such as this:

````
- id: 'sync_bring'
  alias: Sync Bring
  description: ''
  trigger:
  - platform: time_pattern
    hours: '*'
    minutes: /15
    seconds: '0'
  condition: []
  action:
  - service: shopping_list.bring_sync
    data: {}
  mode: single
````

You can learn more about Automations here: https://www.home-assistant.io/docs/automation/basics/ 

As a quick guide:
Go to your automations in HA -> Create a new one -> Choose Time-Pattern -> Trigger every x min the service stated above.
